# url, куда будет приходить регистрация микросервисов
eureka.client.service-url.defaultZone=http://localhost:8081/eureka

# отключение лишних логов, т.к. здесь не создаются и не вызываются микросервисы
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
